name: "Send Email After Workflow"

on:
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2

      - name: "Setup Python Env"
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: "Install Dependencies"
        run: |
          python -m pip install --upgrade pip
          # smtplib and email are part of Python's standard library, no need to install
          pip install requests  # (example: install any extra deps if needed)

      - name: "Send Email by Executing Python Script"
        run: python send_email.py
        env:
          WORKFLOW_NAME: ${{ github.workflow }}
          REPO_NAME: ${{ github.repository }}
          WORKFLOW_RUN_ID: ${{ github.run_id }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
